### ISSUE TITLE
Working with Safari?

### ISSUE THREAD

**Issue by JoshuaCrisp** [chenzlabs/aframe-ar#26]
I cannot get your glitch examples to work in Safari. Neither do the examples on the repo when I clone them to my https server. The models show up, but my camera is not used. Is this expected behavior, or am I doing something wrong?

**Comment by machenmusik** [comment]
Unfortunately, Mobile Safari does not include WebAR support, so that is expected at present.  In the README, WebAR browsers that should work are listed, but the only one for iOS that you can install from App Store directly is Mozilla's WebXR Viewer, AFAIK.  
`Basic A-Frame support for browser-based augmented reality (AR), supporting the new three.ar.js library and WebARonARKit/Core browsers, as well as WebXR Viewer.`
Google's WebARonARKit browser should also work, but you have to build and install it yourself.
