### ISSUE TITLE
image tracking?

### ISSUE THREAD

**Issue by Marcus5234** [chenzlabs/aframe-ar#41]
Is image tracking possible?

**Comment by machenmusik** [comment]
Image tracking had been working with the original experimental browsers, but since they are deprecated now, and I don't think there is image tracking yet in the Chrome WebXR AR support, for now it may only work on Mozilla WebXR Viewer on iOS, and it is possible the internal linkage there broke.  Will try to find some time to look again now that Chrome v81 support is more mature

**Comment by machenmusik** [comment]
TL;DR - before yes, now no, maybe (again) later.

My understanding is that official WebXR spec for this class of functionality is still not available; Mozilla's new 2.0 version of WebXR Viewer now uses the official spec, so the proprietary support for their 1.x versions is no longer compatible.
