### ISSUE TITLE
Mozilla XR viewer compatibility

### ISSUE THREAD

**Issue by frederic-schwarz** [chenzlabs/aframe-ar#9]
Rendering virtual content works but the pass-through camera is currently not displayed in the Mozilla XR viewer.
https://itunes.apple.com/us/app/webxr-viewer/id1295998056
https://github.com/mozilla-mobile/webxr-ios

**Comment by machenmusik** [comment]
Thanks for the bug report - will be looking at this today.

On Sun, Dec 10, 2017 at 11:41 AM, Frederic Schwarz <notifications@github.com

**Comment by machenmusik** [comment]
Basic camera passthrough and pose are working.

Automatic raycaster result append is not possible with the current version of WebXR Viewer, because its hit test is asynchronous; structural changes will be required on the Mozilla side.

Closing for now until it is possible to support more WebXR Viewer features.
